In [167]:
import numpy as np

In [168]:
#first param create number of row
#second param created number of elements in a row : p.zeros && np.ones

In [169]:
np.zeros((3,3))



array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [170]:
#sinle param create a number of element in one array/row : np.zeros && np.ones

In [171]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [172]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [173]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [174]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [194]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [176]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [177]:
np.random.rand(2)

array([0.00465674, 0.03466138])

In [178]:
np.random.rand(5,5)

array([[0.76579508, 0.23184991, 0.54007783, 0.54285488, 0.39200078],
       [0.67172886, 0.44022495, 0.2957961 , 0.35853505, 0.13261148],
       [0.80290145, 0.33352405, 0.32445695, 0.76504575, 0.11386647],
       [0.54549583, 0.18950025, 0.78600815, 0.66748376, 0.59850608],
       [0.17592871, 0.84204589, 0.20724863, 0.9683365 , 0.61042203]])

In [179]:
np.random.randn(50,90)

array([[ 0.52048881,  0.46434936, -0.69591597, ..., -0.34426876,
         1.14113163,  0.51570692],
       [-0.14959364,  0.47954325, -0.3638704 , ...,  0.05435266,
        -2.48388299, -0.75422478],
       [-0.60596187, -1.34798867,  0.32064765, ...,  0.90481133,
        -0.47161555, -1.241427  ],
       ...,
       [-0.05119437, -1.92229038, -0.36312837, ...,  0.65485532,
         0.14207852, -1.0949964 ],
       [ 1.24270309, -0.07591318, -1.21650883, ..., -2.58429577,
         0.98951683, -0.39511998],
       [ 1.30771643, -0.59295608, -0.82496048, ...,  0.63334903,
         0.43237581,  0.77191545]])

In [181]:
np.random.randint(50,90, 10)

array([68, 52, 73, 80, 63, 78, 67, 55, 80, 66])

In [ ]:
arr = np.arange(16)

In [ ]:
arr

In [188]:
arr.reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [183]:
#first start number to be generated
#second end number to be generated
#third create number of elements
ranarr = np.random.randint(25,100,20)

In [184]:
ranarr

array([68, 92, 96, 35, 27, 44, 73, 82, 81, 70, 33, 94, 48, 41, 96, 35, 28,
       64, 85, 70])

In [186]:
ranarr.max()


96

In [187]:
ranarr.min()

27

In [189]:
ranarr.argmax()

2

In [191]:
ranarr.argmin()


4

In [193]:
arr.shape

(16,)

In [208]:
newarr = np.arange(100).reshape(10,10)

In [209]:
newarr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [211]:
newarr.shape


(10, 10)

In [220]:
newarr[:2, 3:5]

array([[ 3,  4],
       [13, 14]])

In [221]:
#setting a value with index range (Broadcasting)

In [223]:
arr[0:5] = 100;

In [224]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15])

In [226]:
copy = newarr.copy()
copy

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [227]:
#slice

bago = np.array(([5,10,15],[20,25,30], [35,40,45]))

In [229]:
bago

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [253]:
bago[:2,1:3]

array([[10, 15],
       [25, 30]])

In [271]:
bago[0:][:3]

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [274]:
bago_2d = np.zeros((10,10)) ;

In [276]:
bago_2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [281]:
bago_2d[[6,4,5,6]]

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [286]:
compare = np.arange(1,11)

In [287]:
compare


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [289]:
bool_arr = compare >4 
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [292]:
compare[bool_arr]


array([ 5,  6,  7,  8,  9, 10])

In [293]:
compare + compare


array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [303]:
hakdog = compare - compare
hakdog

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [297]:
compare * compare


array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

compare**compare

In [298]:
compare**compare

array([         1,          4,         27,        256,       3125,
            46656,     823543,   16777216,  387420489, 1410065408])

In [302]:
compare / hakdog



C:\Users\asus\AppData\Local\Temp\ipykernel_10304\132763187.py:1: RuntimeWarning: divide by zero encountered in true_divide
  compare / hakdog


array([inf, inf, inf, inf, inf, inf, inf, inf, inf, inf])

In [ ]:
#Flash si sir yawa